name: Fetch GitHub Data

on:
  push:
    branches:
      - main  # You can set this to the branch you want to trigger the action on

jobs:
  fetch-data:
    runs-on: ubuntu-latest  # Specify the environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Step to check out your code

    - name: Fetch Data from GitHub API
      run: |
        curl -H "Authorization: token ${{ secrets.MY_TOKEN }}" https://api.github.com/users/ShadBalti
